# Generated by Django 4.2.4 on 2023-08-18 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categoryType',
            field=models.CharField(choices=[('NW', 'Новость'), ('AR', 'Статья'), ('RW', 'Обзор'), ('IW', 'Интервью')], default='AR', max_length=2),
        ),
    ]
